# config/prompts.yaml
document_qa: |
  你是一个文档理解助手。请根据提供的图像内容回答问题。
  问题：{{question}}
  请只回答问题内容，不要解释。

invoice_extraction: |
  请从发票中提取以下字段：
  - 发票号码
  - 开票日期
  - 总金额（含税）
  - 销售方名称
  - 购买方名称
  请以 JSON 格式输出，字段名使用英文：
  {
    "invoice_number": "",
    "issue_date": "",
    "total_amount": 0.0,
    "seller": "",
    "buyer": ""
  }

image_caption: |
  请用一句话描述这张图片的内容。