http_options:
  host: 0.0.0.0
  port: 8101 

applications:
  - name: vlm-app
    route_prefix: /
    import_path: serve_app:create_app
    args:     
      arg1: "1"
      arg2: 2
    runtime_env:
      env_vars:
        CODE_VERSION: '0'
    deployments:
      - name: VLMGateway
        num_replicas: 1
        ray_actor_options:
          cpu: 1
        max_ongoing_requests: 2

      - name: DocumentQADeployment
        num_replicas: 1
        ray_actor_options:
          cpu: 0.5
        max_ongoing_requests: 1

      - name: ImageCaptionDeployment
        num_replicas: 1
        ray_actor_options:
          cpu: 0.5
        max_ongoing_requests: 1

      - name: InvoiceExtractionDeployment
        num_replicas: 1
        ray_actor_options:
          cpu: 0.5
        max_ongoing_requests: 2